skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
compliance_hook = "9AxMnpb5g8c8DSnDHNYEeafiTrSzWZbthoDEQpTKiD5z"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
